### ISSUE TITLE
Development process guidelines

### ISSUE THREAD

**Issue by rexim** [morganey-lang/organization#7]
They should be optional (because per rules PL decides upon the dev process) but adaptable.
### Keep in mind

- [x] #33 Release Process: https://github.com/morganey-lang/Morganey/issues/244
- [x] #34 Issue Tracker Hygiene: https://github.com/morganey-lang/Morganey/pull/243#issuecomment-251353439
- [ ] #21 Label System: https://github.com/morganey-lang/morganey-gradle-plugin/pull/10#issuecomment-251694522
- [ ] #35 Problem Reporting Format: https://github.com/morganey-lang/morganey-gradle-plugin/pull/7#issuecomment-251654159
- [ ] #37 Contribution Protocol: https://github.com/morganey-lang/morganey-gradle-plugin/pull/13#issuecomment-251707375
- [ ] #38 Issue & PR templates: https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by 06needhamt** [comment]
We should implement a Pull Request/Issue template as mentioned here https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by rexim** [comment]
@06needhamt nice idea! The template should be a part of Dev guidelines indeed. :)
